version: '3'

services:
  webserver:
    image: mynginx:v1
    restart: always
    ports:
      - 8081:8080
      - 8082:8081
    volumes:
      - /new-project/:/usr/share/nginx/html
    tty: true

  dbos:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: nihal
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb
    tty: true

  myserver:
    image: php-apache:v1
    restart: always
    depends_on:
      - dbos
    volumes:
      - /var/www/html:/var/www/html
    tty: true    
